# Generated by Django 5.1.7 on 2025-04-30 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='bookswap.factbooklisting'),
        ),
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('horror', 'Horror'), ('thriller', 'Thriller'), ('romance', 'Romance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='factrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Fact_received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Fact_sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(choices=[('horror', 'Horror'), ('thriller', 'Thriller'), ('romance', 'Romance')], max_length=100),
        ),
    ]
